kind: ConfigMap
apiVersion: v1
metadata:
  name: todo-data
  namespace: todo-ns
data:
  db_name: "todo-db"
  db_user: "root"
  db_password: "root"
  db_host: "mysql"
  db_port: "3306"
  ip: "*"
  