kind: Deployment
apiVersion: apps/v1
metadata:
  name: todo-deployment-nginx
  namespace: todo-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-nginx
  template:
    metadata:
      labels:
        app: todo-nginx
    spec:
      containers:
      - name: todo-nginx
        image: akj49/django-nginx:latest
        resources:
          requests:
            cpu: "0.5"
            memory: "50Mi"
          limits:
            cpu: "0.5"
            memory: "100Mi"
        ports:
        - containerPort: 80